version: '3.1'
services:
  db:
    image: mysql
    container_name: greatpowers_db_local
    command: --default-authentication-plugin=greatpowers
    ports:
      - "26281:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'greatpowers'
      MYSQL_USER: 'greatpowers'
      MYSQL_PASSWORD: 'greatpowers'
      MYSQL_ROOT_PASSWORD: 'greatpowers'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./:/var/lib/mysql
volumes:
  greatpowers:
