version: '3.1'
services:
  db:
    image: mysql
    container_name: 'greatpowers_db'
    ports:  
      - "26280:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'greatpowers'
      MYSQL_USER: 'greatpowers'
      MYSQL_PASSWORD: 'greatpowers'
      MYSQL_ROOT_PASSWORD: 'greatpowers'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./default/mysql:/var/lib/mysql
  queue:
    image: rabbitmq:management-alpine
    container_name: 'greatpowers_queue'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: greatpowers
        RABBITMQ_DEFAULT_PASS: greatpowers
        RABBITMQ_DEFAULT_VHOST: greatpowers
    volumes:
      - ./default/rabbitmq:/var/lib/rabbitmq
volumes:
  greatpowers:
