version: '3.1'
services:
  db:
    image: mysql
    container_name: greatpowers_db_default
    command: --default-authentication-plugin=greatpowers
    ports:  
      - "26280:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'greatpowers'
      MYSQL_USER: 'greatpowers'
      MYSQL_PASSWORD: 'greatpowers'
      MYSQL_ROOT_PASSWORD: 'greatpowers'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./default:/var/lib/mysql
  queue:
    image: rabbitmq
    container_name: greatpowers_queue_default
    ports:
      - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: greatpowers
        RABBITMQ_DEFAULT_PASS: greatpowers
        RABBITMQ_DEFAULT_VHOST: greatpowers
    volumes:
      - ./default:/var/lib/rabbitmq
volumes:
  greatpowers:
