namespace Model.Entities.Regions;

public enum ERegion{
    #region Germany

    Germany,
    Poland,
    BalticStates,
    WhiteRussia,
    Ukraine,
    WestRussia,
    Finland,
    Norway,
    BulgariaRomania,
    SouthEurope,
    Italy,
    France,
    NorthWestEurope,
    Morocco,
    Algeria,
    Libya,

    #endregion
    #region Russia
    
    Caucasus,
    Karelia,
    Archangelsk,
    Russia,
    EwenkiAutonomousDistrict,
    Vologda,
    Novosibirsk,
    Kazakhstan,
    Yakutia,
    Buryatia,
    SovietFarEast,

    #endregion
    #region Britain
    
    Egypt,
    Transjordan,
    Persia,
    India,
    Burma,
    WestAustralia,
    EastAustralia,
    NewZealand,
    FrenchMadagascar,
    SouthAfricanUnion,
    Rhodesia,
    BelgianCongo,
    AngloEgyptianSudan,
    ItalianEastAfrica,
    FrenchEquatorialAfrica,
    FrenchWestAfrica,
    Gibraltar,
    UnitedKingdom,
    Iceland,
    EastCanada,
    WestCanada,

    #endregion
    #region USA
    
    Alaska,
    WesternUnitedStates,
    CentralUnitedStates,
    EasternUnitedStates,
    WestIndia,
    EastMexico,
    CentralAmerica,
    Mexico,
    Brazil,
    Greenland,
    MidwayAtoll,
    HawaiiIslands,
    Sinkiang,
    Anhwei,
    Sezuan,
    Yunnan,

    #endregion
    #region Japan
    
    Japan,
    Mandschurei,
    Jiangsu,
    Guandong,
    FrenchIndochinaThailand,
    Malaysia,
    Borneo,
    EastIndia,
    SolomonIslands,
    NewGuinea,
    PhilippineIslands,
    Formosa,
    Okinawa,
    Iwojima,
    Wake,
    CarolineAtoll,

    #endregion
    #region Neutral
    
    Mongolia,
    Himalaya,
    Afghanistan,
    SaudiArabia,
    Turkey,
    Sweden,
    Ireland,
    SpainPortugal,
    Sahara,
    Angola,
    Mozambique,
    Switzerland,
    Venezuela,
    ColombiaEcuador,
    PeruArgentina,
    Chile,

    #endregion
    #region SeeZones
    
    SeeZone1,
    SeeZone2,
    SeeZone3,
    SeeZone4,
    SeeZone5,
    SeeZone6,
    SeeZone7,
    SeeZone8,
    SeeZone9,
    SeeZone10,
    SeeZone11,
    SeeZone12,
    SeeZone13,
    SeeZone14,
    SeeZone15,
    SeeZone16,
    SeeZone17,
    SeeZone18,
    SeeZone19,
    SeeZone20,
    SeeZone21,
    SeeZone22,
    SeeZone23,
    SeeZone24,
    SeeZone25,
    SeeZone26,
    SeeZone27,
    SeeZone28,
    SeeZone29,
    SeeZone30,
    SeeZone31,
    SeeZone32,
    SeeZone33,
    SeeZone34,
    SeeZone35,
    SeeZone36,
    SeeZone37,
    SeeZone38,
    SeeZone39,
    SeeZone40,
    SeeZone41,
    SeeZone42,
    SeeZone43,
    SeeZone44,
    SeeZone45,
    SeeZone46,
    SeeZone47,
    SeeZone48,
    SeeZone49,
    SeeZone50,
    SeeZone51,
    SeeZone52,
    SeeZone53,
    SeeZone54,
    SeeZone55,
    SeeZone56,
    SeeZone57,
    SeeZone58,
    SeeZone59,
    SeeZone60,
    SeeZone61,
    SeeZone62,
    SeeZone63,
    SeeZone64,
    SeeZone65

    #endregion
}